"use client";

import * as React from "react";
import { TelekineticFrame, TelekinesisStage, play } from "@telekinesis/core";
import { sectionTimesheets } from "../telekinesis/sections";

/**
 * Telekinesis authoring primitives for the docs. Registered globally in
 * `mdx-components.tsx`, so any page can use `<Frame>`, `<DemoGif>`, `<Divider>`
 * and `<Header>`. The site forces demo mode (see `layout.tsx`), so every
 * `<Frame>` registers and the motion can play live.
 */

/** Mount once (in the layout): installs the runtime + Studio bridge. */
export function TkStage(): React.ReactElement {
  return <TelekinesisStage />;
}

export interface FrameProps {
  id: string;
  intent?: string;
  allowZoom?: boolean;
  className?: string;
  children?: React.ReactNode;
}

/** Mark a region of a doc as cinematically controllable. */
export function Frame({ id, intent, allowZoom = true, className, children }: FrameProps): React.ReactElement {
  return (
    <TelekineticFrame id={id} intent={intent} allowZoom={allowZoom} className={className}>
      {children}
    </TelekineticFrame>
  );
}

/** The full-width brand header image, for the top of a page. */
export function Header(): React.ReactElement {
  return (
    <img
      src="/telekinesis_header.png"
      alt="Telekinesis — your product films its own demo"
      className="tk-header"
    />
  );
}

/** A decorative section divider rendered from the brand divider image. */
export function Divider(): React.ReactElement {
  return <img src="/telekinesis_divider.png" alt="" aria-hidden className="tk-divider" />;
}

export interface DemoGifProps {
  /** Key into `sectionTimesheets`; also the `/motion/<section>.gif` filename. */
  section: string;
  caption?: string;
  alt?: string;
}

/**
 * The motion example for a section: a pre-recorded looping GIF (generated by
 * `record:motion`) plus a **Play live** button that performs the same timesheet
 * in the page itself — the static image for scanners, live cinema on demand.
 */
export function DemoGif({ section, caption, alt }: DemoGifProps): React.ReactElement {
  const [playing, setPlaying] = React.useState(false);
  const [videoFailed, setVideoFailed] = React.useState(false);
  const [gifMissing, setGifMissing] = React.useState(false);
  const abortRef = React.useRef<AbortController | null>(null);
  const sheet = sectionTimesheets[section];

  React.useEffect(() => () => abortRef.current?.abort(), []);

  const playLive = async (): Promise<void> => {
    if (!sheet) return;
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setPlaying(true);
    try {
      await play(sheet, { mode: "self", sound: false, signal: controller.signal });
    } catch {
      /* aborted */
    } finally {
      if (abortRef.current === controller) setPlaying(false);
    }
  };

  return (
    <figure className="tk-demo">
      <div className="tk-demo-stage">
        {/*
          Web-friendly by default: a tiny, full-quality <video> (webm) that
          autoplays like a GIF. Falls back to the lightweight GIF if the browser
          can't play webm, then to a hint if motion hasn't been recorded yet.
        */}
        {!videoFailed ? (
          <video
            className="tk-demo-video"
            src={`/motion/${section}.webm`}
            autoPlay
            loop
            muted
            playsInline
            preload="metadata"
            aria-label={alt ?? caption ?? `${section} demo`}
            onError={() => setVideoFailed(true)}
          />
        ) : gifMissing ? (
          <div className="tk-demo-missing">
            <span>Motion preview appears after</span>
            <code>pnpm --filter @telekinesis/docs record:motion</code>
          </div>
        ) : (
          <img
            className="tk-demo-gif"
            src={`/motion/${section}.gif`}
            alt={alt ?? caption ?? `${section} demo`}
            loading="lazy"
            onError={() => setGifMissing(true)}
          />
        )}
        {sheet && (
          <button className="tk-demo-play" onClick={playLive} disabled={playing} type="button">
            {playing ? "● Playing…" : "▶ Play live"}
          </button>
        )}
      </div>
      {caption && <figcaption className="tk-demo-caption">{caption}</figcaption>}
    </figure>
  );
}
